# -*- mode: python ; coding: utf-8 -*-
import os

root_dir = os.path.abspath(".")

def _data(src, dst):
    """Add src→dst data file, skipping if src does not exist."""
    path = os.path.join(root_dir, src)
    if os.path.exists(path):
        return (path, dst)
    print(f"  [SKIP] {src} not found, will be downloaded on first use")
    return None

datas = [
    # Mini datasets (always bundled)
    _data("data/humaneval_mini.json", "data"),
    _data("data/mmlu_pro_mini.json", "data"),
    _data("data/ifeval_mini.json", "data"),
    _data("data/aime_mini.json", "data"),
    _data("data/bigcodebench_mini.json", "data"),
    _data("data/bigcodebench_hard_mini.json", "data"),
    _data("data/longbench_v2_mini.json", "data"),
    _data("data/mmmu_pro_mini.json", "data"),
    _data("data/livebench_mini.json", "data"),
    _data("data/livecodebench_mini.json", "data"),
    _data("data/personal_mini.json", "data"),
    _data("data/lite_mini.json", "data"),
    _data("data/code_mini.json", "data"),
    _data("data/reason_mini.json", "data"),
    _data("data/aider_polyglot_mini.json", "data"),
    _data("data/tectonic_mini.json", "data"),
    _data("data/bfcl/bfcl_mini.json", "data/bfcl"),
    _data("data/safety/uncensor_mini.json", "data/safety"),
    _data("data/writing_speed_test_mini.json", "data"),
    _data("data/coding_speed_test_mini.json", "data"),
    _data("data/truthfulqa_mini.json", "data"),
    _data("data/hellaswag_mini.json", "data"),
    _data("data/winogrande_mini.json", "data"),
    _data("data/arc_mini.json", "data"),
    _data("data/commonsenseqa_mini.json", "data"),
    _data("data/long_context_memory_mini.json", "data"),
    _data("data/niahs_mini.json", "data"),
    _data("data/niahs_corpus.json", "data"),
    _data("data/gaia_mini.json", "data"),
    _data("data/taubench_airline_mini.json", "data"),
    _data("data/toolcall_mini.json", "data"),
    # Tau3-Airline runtime files (shared by full + mini runs — not fetched on demand in the .exe)
    _data("data/taubench_airline_db.json", "data"),
    _data("data/taubench_airline_policy.md", "data"),
    _data("data/taubench_airline_user_guidelines.md", "data"),
    # Full datasets — NOT bundled (fetched on first use via dataset installer).
    # Only mini datasets are bundled above.
    # Frontend dist (SPA static files) — bundle entire dist folder
    _data("frontend/dist", "frontend/dist"),
]

# Filter out None entries (missing files)
datas = [d for d in datas if d is not None]

a = Analysis(
    ['benchmax_server.py'],
    pathex=[root_dir],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'httpx',
        'httpx._transports.default',
        'anyio',
        'anyio._backends._asyncio',
        'httpcore',
        'httpcore._backends.anyio',
        'httpcore._backends.sync',
        'sniffio',
        'h11',
        'certifi',
        'idna',
        'websockets',
        'wsproto',
        'pydantic',
        'multipart',
        'aiofiles',
        'starlette',
        'starlette.applications',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.requests',
        'starlette.responses',
        'starlette.concurrency',
        'sqlalchemy',
        'sqlalchemy.ext.declarative',
        'pandas',
        'psutil',
        'GPUtil',
        'numpy',
        'asyncio',
        'pathlib',
        'backend.main',
        'backend.api',
        'backend.operations',
        'backend.config',
        'backend.database',
        'backend.benchmarks.base',
        'backend.benchmarks.humaneval',
        'backend.benchmarks.mmlu_pro',
        'backend.benchmarks.ifeval',
        'backend.benchmarks.aime',
        'backend.benchmarks.bigcodebench',
        'backend.benchmarks.bfcl',
        'backend.benchmarks.uncensor',
        'backend.benchmarks.longbench_v2',
        'backend.benchmarks.aider_polyglot',
        'backend.benchmarks.mmmu_pro',
        'backend.benchmarks.livebench',
        'backend.benchmarks.livecodebench',
        'backend.benchmarks.personal',
        'backend.benchmarks.lite',
        'backend.benchmarks.code_bench',
        'backend.benchmarks.reason_bench',
        'backend.benchmarks.tectonic',
        'backend.benchmarks.speed_test',
        'backend.benchmarks.truthfulqa',
        'backend.benchmarks.hellaswag',
        'backend.benchmarks.winogrande',
        'backend.benchmarks.arc',
        'backend.benchmarks.commonsenseqa',
        'backend.benchmarks.long_context_memory',
        'backend.benchmarks.niahs',
        'backend.benchmarks.gaia',
        'backend.benchmarks.taubench_airline',
        'backend.benchmarks.toolcall',
        'backend.benchmarks.multi_turn_base',
        'backend.sandbox.safe_executor',
        'backend.sandbox.docker_executor',
        'backend.sandbox.appcontainer',
        'backend.sandbox.job_sandbox',
        'backend.sandbox.mitigation',
        'backend.sandbox.bfcl_checker',
        'backend.benchmarks.scoring',
        'backend.benchmarks.mcq',
        'backend.benchmarks.scorer_base',
        'backend.benchmarks.ifeval_official',
        'backend.benchmarks.ifeval_official.instructions',
        'backend.benchmarks.ifeval_official.instructions_registry',
        'backend.benchmarks.ifeval_official.instructions_util',
        'backend.logging_setup',
        'backend.lm_studio.client',
        'backend.telemetry.monitor',
        # Export / serialization deps (auto-detected but ensure bundled)
        'orjson',
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.workbook',
        'openpyxl.styles',
        'openpyxl.utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'notebook',
        'jupyter',
        'IPython',
        'PIL.ImageShow',
        'PIL.ImageQt',
        'gradio',
        'gradio_client',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BenchMax',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    icon=os.path.join(root_dir, "icon.ico"),
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
