# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

root_dir = os.path.abspath(".")

def _data(src, dst):
    """Add src→dst data file, skipping if src does not exist."""
    path = os.path.join(root_dir, src)
    if os.path.exists(path):
        return (path, dst)
    print(f"  [SKIP] {src} not found, will be downloaded on first use")
    return None

datas = [
    # Mini datasets (always bundled)
    _data("data/humaneval_mini.json", "data"),
    _data("data/mmlu_pro_mini.json", "data"),
    _data("data/ifeval_mini.json", "data"),
    _data("data/aime_mini.json", "data"),
    _data("data/bigcodebench_mini.json", "data"),
    _data("data/bigcodebench_hard_mini.json", "data"),
    _data("data/longbench_v2_mini.json", "data"),
    _data("data/mmmu_pro_mini.json", "data"),
    _data("data/livebench_mini.json", "data"),
    _data("data/livecodebench_mini.json", "data"),
    _data("data/personal_mini.json", "data"),
    _data("data/lite_mini.json", "data"),
    _data("data/code_mini.json", "data"),
    _data("data/reason_mini.json", "data"),
    _data("data/aider_polyglot_mini.json", "data"),
    _data("data/tectonic_mini.json", "data"),
    _data("data/mcp_bench/mcp_bench_mini.json", "data/mcp_bench"),
    _data("data/bfcl/bfcl_mini.json", "data/bfcl"),
    _data("data/safety/safety_mini.json", "data/safety"),
    _data("data/writing_speed_test_mini.json", "data"),
    _data("data/coding_speed_test_mini.json", "data"),
    _data("data/truthfulqa_mini.json", "data"),
    # Full datasets (fetched on first use via dataset installer)
    _data("data/humaneval_full.json", "data"),
    _data("data/aime_full.json", "data"),
    _data("data/ifeval_full.json", "data"),
    _data("data/bigcodebench_full.json", "data"),
    _data("data/bigcodebench_hard_full.json", "data"),
    _data("data/livebench_full.json", "data"),
    _data("data/personal_full.json", "data"),
    _data("data/lite_full.json", "data"),
    _data("data/code_full.json", "data"),
    _data("data/reason_full.json", "data"),
    _data("data/tectonic_full.json", "data"),
    _data("data/aider_polyglot_full.json", "data"),
    _data("data/mcp_bench/mcp_bench_full.json", "data/mcp_bench"),
    _data("data/bfcl/bfcl_full.json", "data/bfcl"),
    _data("data/safety/safety_full.json", "data/safety"),
    _data("data/writing_speed_test_full.json", "data"),
    _data("data/coding_speed_test_full.json", "data"),
    _data("data/truthfulqa_full.json", "data"),
    _data("data/mmmu_pro_full.json", "data"),
    _data("data/livecodebench_full.json", "data"),
    # Frontend dist (SPA static files)
    _data("frontend/dist/index.html", "frontend/dist"),
    _data("frontend/dist/assets", "frontend/dist/assets"),
]

# Filter out None entries (missing files)
datas = [d for d in datas if d is not None]

a = Analysis(
    ['benchmax_server.py'],
    pathex=[root_dir],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'httpx',
        'httpx._transports.default',
        'anyio',
        'anyio._backends._asyncio',
        'httpcore',
        'httpcore._backends.anyio',
        'httpcore._backends.sync',
        'sniffio',
        'h11',
        'certifi',
        'idna',
        'websockets',
        'wsproto',
        'pydantic',
        'multipart',
        'aiofiles',
        'starlette',
        'starlette.applications',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.requests',
        'starlette.responses',
        'starlette.concurrency',
        'sqlalchemy',
        'sqlalchemy.ext.declarative',
        'pandas',
        'psutil',
        'GPUtil',
        'numpy',
        'asyncio',
        'pathlib',
        'backend.main',
        'backend.api',
        'backend.operations',
        'backend.config',
        'backend.database',
        'backend.benchmarks.base',
        'backend.benchmarks.humaneval',
        'backend.benchmarks.mmlu_pro',
        'backend.benchmarks.ifeval',
        'backend.benchmarks.aime',
        'backend.benchmarks.bigcodebench',
        'backend.benchmarks.bfcl',
        'backend.benchmarks.mcp_bench',
        'backend.benchmarks.safety',
        'backend.benchmarks.longbench_v2',
        'backend.benchmarks.aider_polyglot',
        'backend.benchmarks.mmmu_pro',
        'backend.benchmarks.livebench',
        'backend.benchmarks.livecodebench',
        'backend.benchmarks.personal',
        'backend.benchmarks.lite',
        'backend.benchmarks.code_bench',
        'backend.benchmarks.reason_bench',
        'backend.benchmarks.tectonic',
        'backend.benchmarks.speed_test',
        'backend.benchmarks.truthfulqa',
        'backend.lm_studio.client',

        'backend.telemetry.monitor',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'notebook',
        'jupyter',
        'IPython',
        'PIL.ImageShow',
        'PIL.ImageQt',
        'gradio',
        'gradio_client',
        'groovy',
        'safehttpx',
        'test',
        'unittest',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BenchMax',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    icon=os.path.join(root_dir, "icon.ico"),
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
