# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

root_dir = os.path.abspath(".")

datas = [
    # Mini datasets (bundled for Quick Test)
    (os.path.join(root_dir, "data", "humaneval_mini.json"), "data"),
    (os.path.join(root_dir, "data", "mmlu_pro_mini.json"), "data"),
    (os.path.join(root_dir, "data", "ifeval_mini.json"), "data"),
    (os.path.join(root_dir, "data", "aime_mini.json"), "data"),
    (os.path.join(root_dir, "data", "bigcodebench_mini.json"), "data"),
    (os.path.join(root_dir, "data", "bigcodebench_hard_mini.json"), "data"),
    (os.path.join(root_dir, "data", "longbench_v2_mini.json"), "data"),
    (os.path.join(root_dir, "data", "mmmu_pro_mini.json"), "data"),
    (os.path.join(root_dir, "data", "livebench_mini.json"), "data"),
    (os.path.join(root_dir, "data", "personal_mini.json"), "data"),
    (os.path.join(root_dir, "data", "lite_mini.json"), "data"),
    (os.path.join(root_dir, "data", "code_mini.json"), "data"),
    (os.path.join(root_dir, "data", "reason_mini.json"), "data"),
    (os.path.join(root_dir, "data", "aider_polyglot_mini.json"), "data"),
    (os.path.join(root_dir, "data", "humaneval_full.json"), "data"),
    (os.path.join(root_dir, "data", "aime_full.json"), "data"),
    (os.path.join(root_dir, "data", "ifeval_full.json"), "data"),
    (os.path.join(root_dir, "data", "bigcodebench_full.json"), "data"),
    (os.path.join(root_dir, "data", "bigcodebench_hard_full.json"), "data"),
    (os.path.join(root_dir, "data", "livebench_full.json"), "data"),
    (os.path.join(root_dir, "data", "personal_full.json"), "data"),
    (os.path.join(root_dir, "data", "lite_full.json"), "data"),
    (os.path.join(root_dir, "data", "code_full.json"), "data"),
    (os.path.join(root_dir, "data", "reason_full.json"), "data"),
    (os.path.join(root_dir, "data", "tectonic_mini.json"), "data"),
    (os.path.join(root_dir, "data", "tectonic_full.json"), "data"),
    (os.path.join(root_dir, "data", "aider_polyglot_full.json"), "data"),
    (os.path.join(root_dir, "data", "mcp_bench", "mcp_bench_mini.json"), os.path.join("data", "mcp_bench")),
    (os.path.join(root_dir, "data", "mcp_bench", "mcp_bench_full.json"), os.path.join("data", "mcp_bench")),
    (os.path.join(root_dir, "data", "bfcl", "bfcl_mini.json"), os.path.join("data", "bfcl")),
    (os.path.join(root_dir, "data", "bfcl", "bfcl_full.json"), os.path.join("data", "bfcl")),
    (os.path.join(root_dir, "data", "safety", "safety_mini.json"), os.path.join("data", "safety")),
    (os.path.join(root_dir, "data", "safety", "safety_full.json"), os.path.join("data", "safety")),
    # Speed test datasets
    (os.path.join(root_dir, "data", "writing_speed_test_mini.json"), "data"),
    (os.path.join(root_dir, "data", "writing_speed_test_full.json"), "data"),
    (os.path.join(root_dir, "data", "coding_speed_test_mini.json"), "data"),
    (os.path.join(root_dir, "data", "coding_speed_test_full.json"), "data"),
    # TruthfulQA datasets
    (os.path.join(root_dir, "data", "truthfulqa_mini.json"), "data"),
    (os.path.join(root_dir, "data", "truthfulqa_full.json"), "data"),
    # MMMU-Pro full dataset
    (os.path.join(root_dir, "data", "mmmu_pro_full.json"), "data"),
    # Frontend dist (SPA static files)
    (os.path.join(root_dir, "frontend", "dist", "index.html"), os.path.join("frontend", "dist")),
    (os.path.join(root_dir, "frontend", "dist", "assets"), os.path.join("frontend", "dist", "assets")),
]

a = Analysis(
    ['benchmax_server.py'],
    pathex=[root_dir],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'httpx',
        'httpx._transports.default',
        'anyio',
        'anyio._backends._asyncio',
        'httpcore',
        'httpcore._backends.anyio',
        'httpcore._backends.sync',
        'sniffio',
        'h11',
        'certifi',
        'idna',
        'websockets',
        'wsproto',
        'pydantic',
        'multipart',
        'aiofiles',
        'starlette',
        'starlette.applications',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.requests',
        'starlette.responses',
        'starlette.concurrency',
        'sqlalchemy',
        'sqlalchemy.ext.declarative',
        'pandas',
        'psutil',
        'GPUtil',
        'numpy',
        'asyncio',
        'pathlib',
        'backend.main',
        'backend.api',
        'backend.operations',
        'backend.config',
        'backend.database',
        'backend.benchmarks.base',
        'backend.benchmarks.humaneval',
        'backend.benchmarks.mmlu_pro',
        'backend.benchmarks.ifeval',
        'backend.benchmarks.aime',
        'backend.benchmarks.bigcodebench',
        'backend.benchmarks.bfcl',
        'backend.benchmarks.mcp_bench',
        'backend.benchmarks.safety',
        'backend.benchmarks.longbench_v2',
        'backend.benchmarks.aider_polyglot',
        'backend.benchmarks.mmmu_pro',
        'backend.benchmarks.livebench',
        'backend.benchmarks.personal',
        'backend.benchmarks.lite',
        'backend.benchmarks.code_bench',
        'backend.benchmarks.reason_bench',
        'backend.benchmarks.tectonic',
        'backend.benchmarks.speed_test',
        'backend.benchmarks.truthfulqa',
        'backend.lm_studio.client',

        'backend.telemetry.monitor',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'notebook',
        'jupyter',
        'IPython',
        'PIL.ImageShow',
        'PIL.ImageQt',
        'gradio',
        'gradio_client',
        'groovy',
        'safehttpx',
        'test',
        'unittest',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BenchMax',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    icon=os.path.join(root_dir, "icon.ico"),
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
