"""Generate C:\Main\BenchMax\data\tectonic_full.json — 300 BenchMax Tectonic questions."""

import json
import os

QUESTIONS = []

# ===== CODING (80 questions) =====

code_qs = [
    ("tectonic_coding_01", "Coding", "code", "Write a Python function called `two_sum` that takes a list of integers `nums` and a target integer. Return indices of the two numbers that add up to target.", "two_sum"),
    ("tectonic_coding_02", "Coding", "code", "Write a function `is_palindrome` that takes a string and returns True if it reads the same forwards and backwards (case-sensitive).", "is_palindrome"),
    ("tectonic_coding_03", "Coding", "code", "Write a function `fibonacci` that returns the nth Fibonacci number (0-indexed: fib(0)=0, fib(1)=1).", "fibonacci"),
    ("tectonic_coding_04", "Coding", "code", "Write a function `merge_sorted` that merges two sorted lists into one sorted list.", "merge_sorted"),
    ("tectonic_coding_05", "Coding", "code", "Write a function `max_subarray_sum` that returns the maximum sum of any contiguous subarray using Kadane's algorithm.", "max_subarray_sum"),
    ("tectonic_coding_06", "Coding", "code", "Write a function `group_anagrams` that groups a list of strings into anagrams.", "group_anagrams"),
    ("tectonic_coding_07", "Coding", "code", "Write a function `longest_common_prefix` that finds the longest common prefix string among an array of strings.", "longest_common_prefix"),
    ("tectonic_coding_08", "Coding", "code", "Write a function `reverse_linked_list` that reverses a singly linked list in-place. Assume ListNode class with val and next.", "reverse_linked_list"),
    ("tectonic_coding_09", "Coding", "code", "Write a function `is_valid_bst` that takes a binary tree node and returns True if it is a valid binary search tree.", "is_valid_bst"),
    ("tectonic_coding_10", "Coding", "code", "Write a function `level_order_traversal` that returns level-order traversal of a binary tree as a list of lists.", "level_order_traversal"),
    ("tectonic_coding_11", "Coding", "code", "Write a function `quick_sort` that sorts a list in-place using the quicksort algorithm.", "quick_sort"),
    ("tectonic_coding_12", "Coding", "code", "Write a function `coin_change` that returns the minimum number of coins needed to make an amount, given a list of coin denominations.", "coin_change"),
    ("tectonic_coding_13", "Coding", "code", "Write a function `longest_increasing_subsequence` that returns the length of the longest strictly increasing subsequence.", "longest_increasing_subsequence"),
    ("tectonic_coding_14", "Coding", "code", "Write a function `top_k_frequent` that returns the k most frequent elements from a list.", "top_k_frequent"),
    ("tectonic_coding_15", "Coding", "code", "Write a function `find_median_sorted` that returns the median of two sorted arrays in O(log(min(m,n))) time.", "find_median_sorted"),
    ("tectonic_coding_16", "Coding", "code", "Write a function `serialize_tree` that serializes a binary tree to a string, and a function `deserialize_tree` that deserializes it back.", "serialize_tree"),
    ("tectonic_coding_17", "Coding", "code", "Write a function `dijkstra` that takes a graph (adjacency list of {node: [(neighbor, weight)]}) and a start node, returning shortest distances to all nodes.", "dijkstra"),
    ("tectonic_coding_18", "Coding", "code", "Write a function `edit_distance` that returns the minimum number of operations (insert, delete, replace) to convert one string to another.", "edit_distance"),
    ("tectonic_coding_19", "Coding", "code", "Write a function `solve_n_queens` that returns all distinct solutions to the N-Queens puzzle for a given n.", "solve_n_queens"),
    ("tectonic_coding_20", "Coding", "code", "Write a function `lru_cache` that implements an LRU cache with get(key) and put(key, value) in O(1) average time.", "lru_cache"),
    ("tectonic_coding_21", "Coding", "code", "Write a function `regex_match` that implements simple regex matching with '.' and '*' wildcards.", "regex_match"),
    ("tectonic_coding_22", "Coding", "code", "Write a function `find_cycle` that detects if a linked list has a cycle using Floyd's algorithm.", "find_cycle"),
    ("tectonic_coding_23", "Coding", "code", "Write a function `three_sum` that returns all unique triplets in an array that sum to zero.", "three_sum"),
    ("tectonic_coding_24", "Coding", "code", "Write a function `max_product_subarray` that returns the maximum product subarray.", "max_product_subarray"),
    ("tectonic_coding_25", "Coding", "code", "Write a function `word_break` that returns True if a string can be segmented into dictionary words.", "word_break"),
    ("tectonic_coding_26", "Coding", "code", "Write a function `num_islands` that counts the number of islands in a binary grid (1=land, 0=water).", "num_islands"),
    ("tectonic_coding_27", "Coding", "code", "Write a function `kth_largest` that returns the kth largest element in an unsorted array using quickselect.", "kth_largest"),
    ("tectonic_coding_28", "Coding", "code", "Write a function `spiral_order` that returns elements of a matrix in spiral order.", "spiral_order"),
    ("tectonic_coding_29", "Coding", "code", "Write a function `trie` that implements a trie (prefix tree) with insert, search, and starts_with methods.", "trie"),
    ("tectonic_coding_30", "Coding", "code", "Write a function `max_path_sum` that returns the maximum path sum in a binary tree (path can start and end at any node).", "max_path_sum"),
    ("tectonic_coding_31", "Coding", "code", "Write a function `rotate_matrix` that rotates an NxN matrix 90 degrees clockwise in-place.", "rotate_matrix"),
    ("tectonic_coding_32", "Coding", "code", "Write a function `sliding_window_max` that returns the maximum element in every sliding window of size k.", "sliding_window_max"),
    ("tectonic_coding_33", "Coding", "code", "Write a function `pow_x_n` that computes x raised to power n in O(log n) time.", "pow_x_n"),
    ("tectonic_coding_34", "Coding", "code", "Write a function `flatten_nested` that flattens a nested list of integers into a single list.", "flatten_nested"),
    ("tectonic_coding_35", "Coding", "code", "Write a function `first_missing_positive` that returns the smallest missing positive integer from an unsorted array.", "first_missing_positive"),
    ("tectonic_coding_36", "Coding", "code", "Write a function `clone_graph` that deep-copies a connected undirected graph (Node class with val and neighbors).", "clone_graph"),
    ("tectonic_coding_37", "Coding", "code", "Write a function `find_all_anagrams` that finds all start indices of anagrams of a pattern in a string.", "find_all_anagrams"),
    ("tectonic_coding_38", "Coding", "code", "Write a function `serialize` that serializes a nested list of integers (like LeetCode's NestedInteger) to a string.", "serialize"),
    ("tectonic_coding_39", "Coding", "code", "Write a function `meeting_rooms_ii` that returns the minimum number of conference rooms needed for an array of meeting intervals.", "meeting_rooms_ii"),
    ("tectonic_coding_40", "Coding", "code", "Write a function `largest_rectangle` that returns the largest rectangle area in a histogram (array of bar heights).", "largest_rectangle"),
    ("tectonic_coding_41", "Coding", "code", "Write a function `permute` that returns all permutations of a list of distinct integers.", "permute"),
    ("tectonic_coding_42", "Coding", "code", "Write a function `subsets` that returns all subsets of a list of distinct integers.", "subsets"),
    ("tectonic_coding_43", "Coding", "code", "Write a function `decode_ways` that returns the number of ways to decode a numeric string (A=1, B=2, ..., Z=26).", "decode_ways"),
    ("tectonic_coding_44", "Coding", "code", "Write a function `is_interleave` that returns True if string s3 is an interleaving of s1 and s2.", "is_interleave"),
    ("tectonic_coding_45", "Coding", "code", "Write a function `topological_sort` that returns a topological ordering of a directed acyclic graph.", "topological_sort"),
    ("tectonic_coding_46", "Coding", "code", "Write a function `min_window_substring` that returns the minimum window in a string that contains all characters of another string.", "min_window_substring"),
    ("tectonic_coding_47", "Coding", "code", "Write a function `partition_equal_subset` that returns True if an array can be partitioned into two equal-sum subsets.", "partition_equal_subset"),
    ("tectonic_coding_48", "Coding", "code", "Write a function `alien_order` that returns the order of letters in an alien language given a sorted dictionary.", "alien_order"),
    ("tectonic_coding_49", "Coding", "code", "Write a function `rabin_karp` that finds all occurrences of a pattern in a text using Rabin-Karp with rolling hash.", "rabin_karp"),
    ("tectonic_coding_50", "Coding", "code", "Write a function `buddy_strings` that returns True if swapping two letters in string A yields string B.", "buddy_strings"),
    ("tectonic_coding_51", "Coding", "code", "Write a function `connecting_cities` that returns the minimum cost to connect all cities (Prim's or Kruskal's algorithm).", "connecting_cities"),
    ("tectonic_coding_52", "Coding", "code", "Write a function `search_rotated` that searches for a target in a rotated sorted array in O(log n).", "search_rotated"),
    ("tectonic_coding_53", "Coding", "code", "Write a function `count_inversions` that counts inversions in an array using divide and conquer.", "count_inversions"),
    ("tectonic_coding_54", "Coding", "code", "Write a function `shortest_path_binary` that returns the shortest path length in a binary matrix (0=passable, 1=blocked).", "shortest_path_binary"),
    ("tectonic_coding_55", "Coding", "code", "Write a function `min_cost_climbing` that returns the minimum cost to reach the top of a staircase given an array of step costs.", "min_cost_climbing"),
    ("tectonic_coding_56", "Coding", "code", "Write a function `max_area` that returns the maximum area of water a container can hold (array of heights).", "max_area"),
    ("tectonic_coding_57", "Coding", "code", "Write a function `combine` that returns all combinations of k numbers from 1 to n.", "combine"),
    ("tectonic_coding_58", "Coding", "code", "Write a function `remove_nth_from_end` that removes the nth node from the end of a linked list in one pass.", "remove_nth_from_end"),
    ("tectonic_coding_59", "Coding", "code", "Write a function `add_two_numbers` that adds two non-negative numbers represented as linked lists (digits in reverse order).", "add_two_numbers"),
    ("tectonic_coding_60", "Coding", "code", "Write a function `balanced_parentheses` that returns True if a string of brackets is balanced.", "balanced_parentheses"),
    ("tectonic_coding_61", "Coding", "code", "Write a function `median_sliding_window` that returns the median of each sliding window of size k.", "median_sliding_window"),
    ("tectonic_coding_62", "Coding", "code", "Write a function `min_path_sum` that returns the minimum path sum from top-left to bottom-right of a grid moving only down or right.", "min_path_sum"),
    ("tectonic_coding_63", "Coding", "code", "Write a function `count_primes` that returns the number of primes less than n using the Sieve of Eratosthenes.", "count_primes"),
    ("tectonic_coding_64", "Coding", "code", "Write a function `find_duplicates` that returns all duplicates in an array where values are in [1, n] in O(n) time and O(1) extra space.", "find_duplicates"),
    ("tectonic_coding_65", "Coding", "code", "Write a function `is_subtree` that returns True if tree B is a subtree of tree A.", "is_subtree"),
    ("tectonic_coding_66", "Coding", "code", "Write a function `all_paths_from_source` that returns all paths from source to target in a DAG.", "all_paths_from_source"),
    ("tectonic_coding_67", "Coding", "code", "Write a function `majority_element` that returns the majority element (occurs more than n/2 times) using Boyer-Moore voting.", "majority_element"),
    ("tectonic_coding_68", "Coding", "code", "Write a function `sort_colors` that sorts an array of 0s, 1s, and 2s in-place (Dutch national flag problem).", "sort_colors"),
    ("tectonic_coding_69", "Coding", "code", "Write a function `length_of_longest_substring` that returns the length of the longest substring without repeating characters.", "length_of_longest_substring"),
    ("tectonic_coding_70", "Coding", "code", "Write a function `search_matrix` that searches for a target in a row-and-column-wise sorted matrix.", "search_matrix"),
    ("tectonic_coding_71", "Coding", "code", "Write a function `next_permutation` that rearranges an array into the next lexicographically greater permutation in-place.", "next_permutation"),
    ("tectonic_coding_72", "Coding", "code", "Write a function `count_and_say` that returns the nth term of the count-and-say sequence.", "count_and_say"),
    ("tectonic_coding_73", "Coding", "code", "Write a function `is_symmetric` that returns True if a binary tree is symmetric around its center.", "is_symmetric"),
    ("tectonic_coding_74", "Coding", "code", "Write a function `copy_list_with_random` that deep-copies a linked list where each node has a random pointer.", "copy_list_with_random"),
    ("tectonic_coding_75", "Coding", "code", "Write a function `eval_rpn` that evaluates a Reverse Polish Notation expression (tokens as list of strings).", "eval_rpn"),
    ("tectonic_coding_76", "Coding", "code", "Write a function `inorder_traversal` that returns the inorder traversal of a binary tree iteratively (not recursively).", "inorder_traversal"),
    ("tectonic_coding_77", "Coding", "code", "Write a function `can_finish_courses` that returns True if all courses can be finished given prerequisites (cycle detection).", "can_finish_courses"),
    ("tectonic_coding_78", "Coding", "code", "Write a function `max_coins` that returns the maximum coins obtainable by bursting balloons (indexed by nums array).", "max_coins"),
    ("tectonic_coding_79", "Coding", "code", "Write a function `is_match_wildcard` that implements wildcard pattern matching with '?' (any char) and '*' (any sequence).", "is_match_wildcard"),
    ("tectonic_coding_80", "Coding", "code", "Write a function `find_peak_element` that returns a peak element index in an array (greater than its neighbors).", "find_peak_element"),
]
for q in code_qs:
    QUESTIONS.append({
        "task_id": q[0],
        "category": q[1],
        "type": q[2],
        "prompt": q[3] + " Provide only the function definition, no test code.",
        "answer": q[4],
    })

# ===== LOGIC/REASONING (80 questions) =====

logic_qs = [
    ("tectonic_logic_01", "Logic/Reasoning", "free_form", "A clock shows 3:15. What is the angle in degrees between the hour and minute hands? Output only the number.", "7.5"),
    ("tectonic_logic_02", "Logic/Reasoning", "free_form", "How many times a day do the hour and minute hands of a clock overlap? Output only the number.", "22"),
    ("tectonic_logic_03", "Logic/Reasoning", "free_form", "You roll two fair six-sided dice. What is the probability the sum is 7? Output as a simplified fraction.", "1/6"),
    ("tectonic_logic_04", "Logic/Reasoning", "free_form", "A number increased by 25% and then decreased by 20% gives 100. What was the original number? Output only the number.", "100"),
    ("tectonic_logic_05", "Logic/Reasoning", "free_form", "Solve: 5 + 3 * 2^2 - 1. Output only the number.", "16"),
    ("tectonic_logic_06", "Logic/Reasoning", "free_form", "A ladder 13 feet long rests against a vertical wall. If the bottom of the ladder slides away at 2 ft/s, how fast is the top sliding down when the bottom is 5 ft from the wall in ft/s? Output only the number.", "5/6"),
    ("tectonic_logic_07", "Logic/Reasoning", "free_form", "Alice, Bob, and Charlie each have a different job (Engineer, Doctor, Teacher). Bob is not the Doctor. Charlie is not the Teacher or Engineer. Who is the Engineer? Output only the name.", "Alice"),
    ("tectonic_logic_08", "Logic/Reasoning", "free_form", "In a group of 40 people, 28 like chocolate, 15 like vanilla, and 10 like both. How many like neither? Output only the number.", "7"),
    ("tectonic_logic_09", "Logic/Reasoning", "free_form", "A pizza has a diameter of 12 inches. What is its area in square inches? Use pi=3.14. Output only the number.", "113.04"),
    ("tectonic_logic_10", "Logic/Reasoning", "free_form", "We have 100 kg of berries with 99% water content. After drying, water content drops to 98%. What is the new weight in kg? Output only the number.", "50"),
    ("tectonic_logic_11", "Logic/Reasoning", "free_form", "Two trains 200m and 300m long are moving toward each other at 60 km/h and 40 km/h. How many seconds until they completely pass each other? Output only the number.", "18"),
    ("tectonic_logic_12", "Logic/Reasoning", "free_form", "A man buys a horse for $60, sells it for $70, buys it back for $80, sells it again for $90. What is his total profit in dollars? Output only the number.", "20"),
    ("tectonic_logic_13", "Logic/Reasoning", "free_form", "If 6 cats catch 6 mice in 6 minutes, how many cats are needed to catch 60 mice in 60 minutes? Output only the number.", "6"),
    ("tectonic_logic_14", "Logic/Reasoning", "free_form", "A frog is at the bottom of a 30m well. Each day it climbs 3m and slips 2m at night. How many days to reach the top? Output only the number.", "28"),
    ("tectonic_logic_15", "Logic/Reasoning", "free_form", "There are 5 sisters. Each has a brother. How many siblings total? Output only the number.", "6"),
    ("tectonic_logic_16", "Logic/Reasoning", "free_form", "Half of 2 + 2 = ? Output only the number.", "3"),
    ("tectonic_logic_17", "Logic/Reasoning", "free_form", "A plane crashes exactly on the border of the US and Canada. Where do they bury the survivors? Answer with the phrase: 'survivors not buried'", "survivors not buried"),
    ("tectonic_logic_18", "Logic/Reasoning", "free_form", "What has keys but can't open locks? Output only the single word.", "piano"),
    ("tectonic_logic_19", "Logic/Reasoning", "free_form", "What is the 7th term in the sequence: 1, 1, 2, 3, 5, 8, ? Output only the number.", "13"),
    ("tectonic_logic_20", "Logic/Reasoning", "free_form", "How many squares (of all sizes) are on a chessboard? Output only the number.", "204"),
    ("tectonic_logic_21", "Logic/Reasoning", "free_form", "A 10m rope ladder hangs over the side of a ship, with rungs 1m apart. The bottom rung touches the water. If the tide rises at 0.5m per hour, after how many hours will the 4th rung from the bottom touch the water? Output only the number.", "0"),
    ("tectonic_logic_22", "Logic/Reasoning", "free_form", "If April 1 is a Monday, what day of the week is April 30? Output only the day name.", "Tuesday"),
    ("tectonic_logic_23", "Logic/Reasoning", "free_form", "What is the sum of the first 20 odd numbers? Output only the number.", "400"),
    ("tectonic_logic_24", "Logic/Reasoning", "free_form", "A train passes a pole in 15 seconds and a 100m platform in 25 seconds. What is the train's length in meters? Output only the number.", "150"),
    ("tectonic_logic_25", "Logic/Reasoning", "free_form", "If 3 men can build a wall in 4 days, how many men are needed to build the same wall in half a day? Output only the number.", "24"),
    ("tectonic_logic_26", "Logic/Reasoning", "free_form", "In a class, the number of girls is twice the number of boys. The total number of students is 36. How many boys are there? Output only the number.", "12"),
    ("tectonic_logic_27", "Logic/Reasoning", "free_form", "The difference between a two-digit number and its reverse is 27. The sum of its digits is 9. What is the number? Output only the number.", "63"),
    ("tectonic_logic_28", "Logic/Reasoning", "free_form", "How many edges does a cube have? Output only the number.", "12"),
    ("tectonic_logic_29", "Logic/Reasoning", "free_form", "A man walks 5 km north, 3 km east, 5 km south, and 3 km west. How far from the start point in km? Output only the number.", "0"),
    ("tectonic_logic_30", "Logic/Reasoning", "free_form", "If you multiply the age of a father and son you get 520. The father is 18 years older. How old is the son? Output only the number.", "20"),
    ("tectonic_logic_31", "Logic/Reasoning", "free_form", "321 + 123 = ? Output only the number.", "444"),
    ("tectonic_logic_32", "Logic/Reasoning", "free_form", "There are 100 houses in a row numbered 1 to 100. How many houses have the digit 9 in their number? Output only the number.", "19"),
    ("tectonic_logic_33", "Logic/Reasoning", "free_form", "Fill in the blank: 1, 4, 9, 16, 25, ? Output only the number.", "36"),
    ("tectonic_logic_34", "Logic/Reasoning", "free_form", "A bacteria doubles every hour. It takes 48 hours to fill a jar. When was the jar half-full? Output: '47 hours'", "47 hours"),
    ("tectonic_logic_35", "Logic/Reasoning", "free_form", "How many months have 31 days in a regular year? Output only the number.", "7"),
    ("tectonic_logic_36", "Logic/Reasoning", "free_form", "A bottle and a cork cost $1.05. The bottle costs $1 more than the cork. How much does the cork cost in cents? Output only the number.", "2.5"),
    ("tectonic_logic_37", "Logic/Reasoning", "free_form", "What is 15% of 200? Output only the number.", "30"),
    ("tectonic_logic_38", "Logic/Reasoning", "free_form", "1 + 1 + 1 + 1 + 1 + 1 * 0 = ? Output only the number.", "5"),
    ("tectonic_logic_39", "Logic/Reasoning", "free_form", "Find the missing number: 72, 56, 42, 30, 20, ? Output only the number.", "12"),
    ("tectonic_logic_40", "Logic/Reasoning", "free_form", "A rectangle has length 12 and area 96. What is the perimeter? Output only the number.", "40"),
    ("tectonic_logic_41", "Logic/Reasoning", "free_form", "Which number is the odd one out: 3, 5, 7, 11, 13, 17, 19, 21? Output only the number.", "21"),
    ("tectonic_logic_42", "Logic/Reasoning", "free_form", "The average of 5 numbers is 15. If one number is removed, the average becomes 12. What was the removed number? Output only the number.", "27"),
    ("tectonic_logic_43", "Logic/Reasoning", "free_form", "A cuboid has dimensions 3x4x5. What is its diagonal length? Round to 1 decimal place. Output only the number.", "7.1"),
    ("tectonic_logic_44", "Logic/Reasoning", "free_form", "A man counts 20 cows, 30 chickens, and 15 dogs on his farm. How many legs? Output only the number.", "220"),
    ("tectonic_logic_45", "Logic/Reasoning", "free_form", "Today is Friday. What day of the week will it be in 100 days? Output only the day name.", "Sunday"),
    ("tectonic_logic_46", "Logic/Reasoning", "free_form", "How many degrees are in a triangle? Output only the number.", "180"),
    ("tectonic_logic_47", "Logic/Reasoning", "free_form", "The sum of two numbers is 20, and their product is 96. What is the larger number? Output only the number.", "12"),
    ("tectonic_logic_48", "Logic/Reasoning", "free_form", "A ball is thrown upward at 20 m/s. How many seconds until it returns to the starting point? g=10 m/s^2. Output only the number.", "4"),
    ("tectonic_logic_49", "Logic/Reasoning", "free_form", "What is the Roman numeral for 99? Output just the Roman numeral.", "XCIX"),
    ("tectonic_logic_50", "Logic/Reasoning", "free_form", "If a=5, b=10, c=3, what is (a+b)*c - a? Output only the number.", "40"),
    ("tectonic_logic_51", "Logic/Reasoning", "free_form", "How many cubic centimeters in a liter? Output only the number.", "1000"),
    ("tectonic_logic_52", "Logic/Reasoning", "free_form", "Which month comes 3 months after September? Output only the month name.", "December"),
    ("tectonic_logic_53", "Logic/Reasoning", "free_form", "A card is drawn from a standard 52-card deck. What is the probability it is a heart? Output as a simplified fraction.", "1/4"),
    ("tectonic_logic_54", "Logic/Reasoning", "free_form", "The sum of the interior angles of a hexagon in degrees? Output only the number.", "720"),
    ("tectonic_logic_55", "Logic/Reasoning", "free_form", "How many zeroes at the end of 1000!? Hint: count trailing zeros. Output only the number.", "249"),
    ("tectonic_logic_56", "Logic/Reasoning", "free_form", "Three people split a $45 dinner bill evenly. One person has a $10 coupon. How much does the person with the coupon pay in dollars? Output only the number.", "5"),
    ("tectonic_logic_57", "Logic/Reasoning", "free_form", "If 1=3, 2=6, 3=9, 4=12, what does 5 equal? Output only the number.", "15"),
    ("tectonic_logic_58", "Logic/Reasoning", "free_form", "A car covers 240 km at 60 km/h and returns at 40 km/h. What is the average speed for the round trip in km/h? Output only the number.", "48"),
    ("tectonic_logic_59", "Logic/Reasoning", "free_form", "Complete: 1, 2, 4, 7, 11, 16, ? Output only the number.", "22"),
    ("tectonic_logic_60", "Logic/Reasoning", "free_form", "How many diagonals does a pentagon have? Output only the number.", "5"),
    ("tectonic_logic_61", "Logic/Reasoning", "free_form", "A father is 4 times as old as his son. In 20 years, he will be twice as old. How old is the son? Output only the number.", "10"),
    ("tectonic_logic_62", "Logic/Reasoning", "free_form", "What is the digital root of 999,999? Output only the digit.", "9"),
    ("tectonic_logic_63", "Logic/Reasoning", "free_form", "If it's 3 o'clock, how many degrees between the two hands? Output only the number.", "90"),
    ("tectonic_logic_64", "Logic/Reasoning", "free_form", "A discount of 40% followed by another 20% is equivalent to what single discount percentage? Output only the number.", "52"),
    ("tectonic_logic_65", "Logic/Reasoning", "free_form", "You need 1 cup of milk. You have a 3/4 cup and a 1/3 cup measure. Which combination works? Answer: '3/4 minus 1/3' or 'fill 3/4 then remove 1/3' or similar describing the operation.", "fill 3/4 then remove 1/3"),
    ("tectonic_logic_66", "Logic/Reasoning", "free_form", "In a triangle, angles are in the ratio 2:3:4. What is the largest angle in degrees? Output only the number.", "80"),
    ("tectonic_logic_67", "Logic/Reasoning", "free_form", "A stock is worth $100. It goes up 10% then down 10%. What is its final value in dollars? Output only the number.", "99"),
    ("tectonic_logic_68", "Logic/Reasoning", "free_form", "How many times can you subtract 5 from 25? Output only the phrase: 'once' or 'five times' or the correct answer.", "once"),
    ("tectonic_logic_69", "Logic/Reasoning", "free_form", "A grandfather, two fathers, and two sons go to a movie. Each buys a ticket. Minimum number of tickets? Output only the number.", "3"),
    ("tectonic_logic_70", "Logic/Reasoning", "free_form", "What is the smallest positive integer that is divisible by all numbers from 1 to 10? Output only the number.", "2520"),
    ("tectonic_logic_71", "Logic/Reasoning", "free_form", "If you reverse the digits of a number, it becomes 2/5 of the original. The digits sum to 9. What is the number? Output only the number.", "45"),
    ("tectonic_logic_72", "Logic/Reasoning", "free_form", "How many integers between 1 and 100 are divisible by 3 or 5? Output only the number.", "47"),
    ("tectonic_logic_73", "Logic/Reasoning", "free_form", "What number, when squared, gives 0.25? Output only the number.", "0.5"),
    ("tectonic_logic_74", "Logic/Reasoning", "free_form", "A bowl contains 100 marbles — 50 black and 50 white. You draw 2 without replacement. What is the probability both are the same color? Output as a simplified fraction.", "49/99"),
    ("tectonic_logic_75", "Logic/Reasoning", "free_form", "I am an odd number. Take away a letter and I become even. What number am I? Output only the digit word (e.g., 'seven').", "seven"),
    ("tectonic_logic_76", "Logic/Reasoning", "free_form", "The radius of a circle is increased by 100%. By what percentage does the area increase? Output only the number (the percentage).", "300"),
    ("tectonic_logic_77", "Logic/Reasoning", "free_form", "If a:b = 2:3 and b:c = 4:5, what is a:c? Output the ratio in simplest form like '8:15' or similar.", "8:15"),
    ("tectonic_logic_78", "Logic/Reasoning", "free_form", "In how many years will $1000 double at 7.2% annual compound interest? Use the rule of 72. Output only the number.", "10"),
    ("tectonic_logic_79", "Logic/Reasoning", "free_form", "3 liters of 20% saline is mixed with 2 liters of 30% saline. What is the final saline percentage? Output only the number.", "24"),
    ("tectonic_logic_80", "Logic/Reasoning", "free_form", "Complete the sequence: A, E, F, H, I, K, L, M, N, ? What is the next letter? (Hint: look at letter shapes). Output only the uppercase letter.", "T"),
]
for q in logic_qs:
    QUESTIONS.append({
        "task_id": q[0],
        "category": q[1],
        "type": q[2],
        "prompt": q[3],
        "answer": q[4],
    })

# ===== INSTRUCTION FOLLOWING (60 questions) =====

inst_qs = [
    ("tectonic_inst_01", "Instruction Following", "free_form", "Write exactly one sentence that contains the words 'benchmark', 'evaluate', and 'tectonic' in that order. Do not write anything else.", "benchmark evaluate tectonic"),
    ("tectonic_inst_02", "Instruction Following", "free_form", 'Output a JSON object with exactly two keys: "name" (your response is a string) and "count" (an integer). The value of "count" must be 42. Nothing else.', '"count": 42'),
    ("tectonic_inst_03", "Instruction Following", "free_form", "Output exactly 10 words. Count them carefully before outputting. Nothing more, nothing less.", "exactly"),
    ("tectonic_inst_04", "Instruction Following", "free_form", "Write a Python one-liner (single line of code) that checks if a string is a palindrome. Output ONLY the line of code, nothing else.", "def is_palindrome"),
    ("tectonic_inst_05", "Instruction Following", "free_form", "List exactly 5 prime numbers less than 30, separated by commas. No other text.", "2, 3, 5, 7, 11"),
    ("tectonic_inst_06", "Instruction Following", "free_form", "Start your response with the word 'APPLE'. End your response with the word 'ZEBRA'. Your total response must be between 5 and 10 words long.", "APPLE"),
    ("tectonic_inst_07", "Instruction Following", "free_form", "Output the number 3250 in binary (base-2). Output ONLY the binary string, no other text.", "110010110010"),
    ("tectonic_inst_08", "Instruction Following", "free_form", "Capitalize every word in this sentence: 'the quick brown fox jumps over the lazy dog'. Output only the capitalized sentence.", "The Quick Brown Fox Jumps Over The Lazy Dog"),
    ("tectonic_inst_09", "Instruction Following", "free_form", "Write a response where every word starts with the letter 's'. Minimum 5 words. Output only the words.", "s"),
    ("tectonic_inst_10", "Instruction Following", "free_form", "Output a single JSON array containing the numbers 5, 10, 15, 20, 25. No other text.", "[5, 10, 15, 20, 25]"),
    ("tectonic_inst_11", "Instruction Following", "free_form", 'Output exactly this: "Hello World!" (with the quotes).', '"Hello World!"'),
    ("tectonic_inst_12", "Instruction Following", "free_form", "Write a math expression whose result equals 100. Use at least three different arithmetic operators. Output only the expression.", "expression"),
    ("tectonic_inst_13", "Instruction Following", "free_form", "Create a haiku about artificial intelligence (3 lines, 5-7-5 syllables). Output the haiku only.", "5-7-5"),
    ("tectonic_inst_14", "Instruction Following", "free_form", "Output the alphabet in reverse order (Z to A) as a single string without spaces.", "ZYXWVUTSRQPONMLKJIHGFEDCBA"),
    ("tectonic_inst_15", "Instruction Following", "free_form", "Write a to-do list with exactly 4 items numbered 1-4. Each item must be exactly 3 words long. Output only the list.", "1."),
    ("tectonic_inst_16", "Instruction Following", "free_form", "Count from 1 to 10 in binary, each on a new line. Output only the binary numbers, one per line.", "1"),
    ("tectonic_inst_17", "Instruction Following", "free_form", "Generate a valid UUID v4 (random format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx). Output only the UUID.", "4xxx"),
    ("tectonic_inst_18", "Instruction Following", "free_form", "Write a sentence that starts with 'The' and ends with 'end.' and contains exactly 7 words. Count carefully.", "end."),
    ("tectonic_inst_19", "Instruction Following", "free_form", "Output the first 10 prime numbers as a comma-separated list. Nothing else.", "2, 3, 5, 7, 11, 13, 17, 19, 23, 29"),
    ("tectonic_inst_20", "Instruction Following", "free_form", "Write a rhyming couplet (two lines) about algorithms. Each line must have exactly 8 syllables. Output only the couplet.", "couplet"),
    ("tectonic_inst_21", "Instruction Following", "free_form", 'Output a JSON object with a key "message" whose value is a string of exactly 20 characters. Count carefully.', '"message"'),
    ("tectonic_inst_22", "Instruction Following", "free_form", "Write 'Yes' if 2+2=4, otherwise write 'No'. Output only Yes or No.", "Yes"),
    ("tectonic_inst_23", "Instruction Following", "free_form", "Write exactly 3 mathematical equations, each on its own line, where each equation evaluates to 5. Output only the equations.", "5"),
    ("tectonic_inst_24", "Instruction Following", "free_form", "Output each letter of the word 'BENCHMARK' on a separate line in reverse order. Only output the letters.", "K"),
    ("tectonic_inst_25", "Instruction Following", "free_form", "Write a single HTML paragraph element containing the text 'Hello, World!' with the paragraph tag colored red. Output only the HTML.", "<p"),
    ("tectonic_inst_26", "Instruction Following", "free_form", "Create an acronym from the phrase 'Artificially Generated Learning Optimization'. Output only the uppercase acronym.", "AGLO"),
    ("tectonic_inst_27", "Instruction Following", "free_form", "Sort the following numbers in ascending order: 37, 12, 89, 5, 63, 21, 44. Output only the sorted comma-separated list.", "5, 12, 21, 37, 44, 63, 89"),
    ("tectonic_inst_28", "Instruction Following", "free_form", "Write exactly 5 words that are all synonyms for 'intelligent'. Separate them with commas.", "intelligent"),
    ("tectonic_inst_29", "Instruction Following", "free_form", "Output the result of 2^10 computed step by step. Then on the final line output only the final answer. The final line must be just the number.", "1024"),
    ("tectonic_inst_30", "Instruction Following", "free_form", "Write a palindrome sentence (reads same forwards and backwards ignoring case and spaces) of at least 5 words. Output the sentence only.", "palindrome"),
    ("tectonic_inst_31", "Instruction Following", "free_form", "Extract all email addresses from this text and output them separated by commas: 'Contact john@test.com or support@example.com for help. Also try admin@site.org.' Output only the emails.", "john@test.com,support@example.com,admin@site.org"),
    ("tectonic_inst_32", "Instruction Following", "free_form", "Generate a random 8-character password containing at least one uppercase, one lowercase, one digit, and one special character. Output only the password.", "password"),
    ("tectonic_inst_33", "Instruction Following", "free_form", "Write a SQL query that selects all columns from a table named 'users' where the age > 21. Output only the SQL query.", "SELECT"),
    ("tectonic_inst_34", "Instruction Following", "free_form", "Output the 12th Fibonacci number. Output ONLY the number, no other text.", "144"),
    ("tectonic_inst_35", "Instruction Following", "free_form", "List exactly 4 continents whose names start with 'A', separated by commas. Output only the list.", "Asia, Africa, Australia, Antarctica"),
    ("tectonic_inst_36", "Instruction Following", "free_form", "Write a response where each word has exactly 4 letters. Minimum 5 words. Output only the words.", "word"),
    ("tectonic_inst_37", "Instruction Following", "free_form", "Output the MD5 hash of the string 'benchmax' (lowercase). Output only the 32-character hex hash.", "md5"),
    ("tectonic_inst_38", "Instruction Following", "free_form", "Write an instruction that contains the word 'must' exactly three times. Output only the instruction.", "must"),
    ("tectonic_inst_39", "Instruction Following", "free_form", "Output an array of 5 random integers between 1 and 100, formatted as a JSON array. No other text.", "[1"),
    ("tectonic_inst_40", "Instruction Following", "free_form", "Write a sentence with exactly 15 characters (counting letters and spaces). Output the sentence only.", "character"),
    ("tectonic_inst_41", "Instruction Following", "free_form", "Output only: 'This sentence has exactly twenty characters.' Count: T-h-i-s space s-e-n-t-e-n-c-e space h-a-s space e-x-a-c-t-l-y space t-w-e-n-t-y space c-h-a-r-a-c-t-e-r-s period.", "exactly"),
    ("tectonic_inst_42", "Instruction Following", "free_form", "Translate 'hello' into 5 different languages, each separated by a comma. Output only the translations.", "hello"),
    ("tectonic_inst_43", "Instruction Following", "free_form", 'Write a JSON object representing a person with keys "name", "age", and "hobbies" (array). "age" must be 28. Output only the JSON.', '"age": 28'),
    ("tectonic_inst_44", "Instruction Following", "free_form", "Write a sentence that does NOT contain the letter 'e'. Minimum 5 words. Output only the sentence.", "sentence"),
    ("tectonic_inst_45", "Instruction Following", "free_form", "Output the result of 1234 * 4321 as a single number. No other text.", "5332114"),
    ("tectonic_inst_46", "Instruction Following", "free_form", "Write exactly 3 compound words that start with 'every'. Output them separated by commas.", "every"),
    ("tectonic_inst_47", "Instruction Following", "free_form", "Output the following sequence exactly: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. Each number on its own line. No other text.", "10"),
    ("tectonic_inst_48", "Instruction Following", "free_form", "Write a short bio about yourself in exactly 3 sentences. The first sentence must end with a question mark.", "?"),
    ("tectonic_inst_49", "Instruction Following", "free_form", "Replace every occurrence of the word 'cat' with 'dog' in this sentence: 'The cat sat on the mat with another cat.' Output only the modified sentence.", "dog"),
    ("tectonic_inst_50", "Instruction Following", "free_form", 'Create a JSON array of 3 objects, each with keys "x" (integer) and "y" (integer) where each x is less than each y. Output only the JSON.', '"x"'),
    ("tectonic_inst_51", "Instruction Following", "free_form", "Write a command-line instruction that would create a directory named 'test_dir' and then navigate into it. Output only the commands.", "mkdir test_dir"),
    ("tectonic_inst_52", "Instruction Following", "free_form", "Output exactly 7 asterisks (stars) on a single line. No other text.", "*******"),
    ("tectonic_inst_53", "Instruction Following", "free_form", "Write a sentence where the third word is 'always'. Output only the sentence.", "always"),
    ("tectonic_inst_54", "Instruction Following", "free_form", "Output the chemical elements H, He, Li, Be, B, C, N, O, F, Ne in order, each separated by a comma. Output only the comma-separated list.", "H, He, Li, Be, B, C, N, O, F, Ne"),
    ("tectonic_inst_55", "Instruction Following", "free_form", "Write a filename (including extension) that is exactly 12 characters long. Output only the filename.", "filename"),
    ("tectonic_inst_56", "Instruction Following", "free_form", 'Output exactly: {"key1": "value1", "key2": "value2"} formatted with no extra whitespace.', '"key1": "value1"'),
    ("tectonic_inst_57", "Instruction Following", "free_form", "List 3 cities that start and end with the same letter. Output each city on a new line, no extra text.", "city"),
    ("tectonic_inst_58", "Instruction Following", "free_form", "Write a sentence where every word is a palindrome (e.g., 'level'). Minimum 3 words. Output only the words.", "level"),
    ("tectonic_inst_59", "Instruction Following", "free_form", "Output a valid credit card number that passes the Luhn checksum. Format as 16 digits with spaces every 4 digits. Output only the number.", "credit card"),
    ("tectonic_inst_60", "Instruction Following", "free_form", "Combine the words 'think', 'code', 'test', 'deploy' into a single string where each word is separated by a single dash. Output only the result.", "think-code-test-deploy"),
]
for q in inst_qs:
    QUESTIONS.append({
        "task_id": q[0],
        "category": q[1],
        "type": q[2],
        "prompt": q[3],
        "answer": q[4],
    })

# ===== KNOWLEDGE (40 questions) — STEM MCQ A/B/C/D =====

know_qs = [
    ("tectonic_know_01", "Knowledge", "mcq", "What is the speed of light in a vacuum (approximately)?\nA) 3 × 10^6 m/s\nB) 3 × 10^8 m/s\nC) 3 × 10^10 m/s\nD) 3 × 10^4 m/s\nOutput only the letter (A, B, C, or D).", "B"),
    ("tectonic_know_02", "Knowledge", "mcq", "What is the atomic number of Carbon?\nA) 4\nB) 6\nC) 8\nD) 12\nOutput only the letter.", "B"),
    ("tectonic_know_03", "Knowledge", "mcq", "What is the boiling point of water at sea level in Celsius?\nA) 90\nB) 100\nC) 110\nD) 120\nOutput only the letter.", "B"),
    ("tectonic_know_04", "Knowledge", "mcq", "Which planet has the most moons in our solar system?\nA) Jupiter\nB) Saturn\nC) Uranus\nD) Neptune\nOutput only the letter.", "B"),
    ("tectonic_know_05", "Knowledge", "mcq", "What is the derivative of x^3?\nA) 2x\nB) 3x^2\nC) x^2\nD) 3x\nOutput only the letter.", "B"),
    ("tectonic_know_06", "Knowledge", "mcq", "Which element has the chemical symbol 'Fe'?\nA) Francium\nB) Iron\nC) Fluorine\nD) Fermium\nOutput only the letter.", "B"),
    ("tectonic_know_07", "Knowledge", "mcq", "What is the integral of 1/x dx?\nA) x + C\nB) ln(x) + C\nC) e^x + C\nD) 1/x^2 + C\nOutput only the letter.", "B"),
    ("tectonic_know_08", "Knowledge", "mcq", "What is the pH of pure water at 25°C?\nA) 6\nB) 7\nC) 8\nD) 5\nOutput only the letter.", "B"),
    ("tectonic_know_09", "Knowledge", "mcq", "What is the SI unit of force?\nA) Joule\nB) Newton\nC) Watt\nD) Pascal\nOutput only the letter.", "B"),
    ("tectonic_know_10", "Knowledge", "mcq", "What is the largest organ in the human body?\nA) Liver\nB) Skin\nC) Brain\nD) Heart\nOutput only the letter.", "B"),
    ("tectonic_know_11", "Knowledge", "mcq", "What is the chemical formula for methane?\nA) CH3\nB) CH4\nC) C2H4\nD) C2H6\nOutput only the letter.", "B"),
    ("tectonic_know_12", "Knowledge", "mcq", "What is the powerhouse of the cell?\nA) Nucleus\nB) Mitochondria\nC) Ribosome\nD) Golgi apparatus\nOutput only the letter.", "B"),
    ("tectonic_know_13", "Knowledge", "mcq", "What is the square root of 169?\nA) 11\nB) 12\nC) 13\nD) 14\nOutput only the letter.", "C"),
    ("tectonic_know_14", "Knowledge", "mcq", "Which law states that energy cannot be created or destroyed?\nA) Newton's First Law\nB) First Law of Thermodynamics\nC) Second Law of Thermodynamics\nD) Law of Conservation of Mass\nOutput only the letter.", "B"),
    ("tectonic_know_15", "Knowledge", "mcq", "What is the most abundant gas in Earth's atmosphere?\nA) Oxygen\nB) Carbon Dioxide\nC) Nitrogen\nD) Argon\nOutput only the letter.", "C"),
    ("tectonic_know_16", "Knowledge", "mcq", "What is the value of pi to 4 decimal places?\nA) 3.1415\nB) 3.1416\nC) 3.1419\nD) 3.1421\nOutput only the letter.", "B"),
    ("tectonic_know_17", "Knowledge", "mcq", "What is the chemical symbol for gold?\nA) Go\nB) Gd\nC) Au\nD) Ag\nOutput only the letter.", "C"),
    ("tectonic_know_18", "Knowledge", "mcq", "What is the formula for kinetic energy?\nA) mv\nB) mv^2\nC) 1/2 mv^2\nD) 1/2 mv\nOutput only the letter.", "C"),
    ("tectonic_know_19", "Knowledge", "mcq", "How many bones are in the adult human body?\nA) 186\nB) 196\nC) 206\nD) 216\nOutput only the letter.", "C"),
    ("tectonic_know_20", "Knowledge", "mcq", "What is the wavelength range of visible light in nanometers?\nA) 100-400\nB) 400-700\nC) 700-1000\nD) 1000-1300\nOutput only the letter.", "B"),
    ("tectonic_know_21", "Knowledge", "mcq", "What is the chemical name of common table salt?\nA) Potassium Chloride\nB) Calcium Carbonate\nC) Sodium Chloride\nD) Sodium Bicarbonate\nOutput only the letter.", "C"),
    ("tectonic_know_22", "Knowledge", "mcq", "What is the atomic mass of Oxygen (rounded to nearest integer)?\nA) 14\nB) 15\nC) 16\nD) 18\nOutput only the letter.", "C"),
    ("tectonic_know_23", "Knowledge", "mcq", "What galaxy is Earth located in?\nA) Andromeda\nB) Triangulum\nC) Milky Way\nD) Sombrero\nOutput only the letter.", "C"),
    ("tectonic_know_24", "Knowledge", "mcq", "What is the value of cos(0)?\nA) 0\nB) 0.5\nC) 1\nD) -1\nOutput only the letter.", "C"),
    ("tectonic_know_25", "Knowledge", "mcq", "What is the base of the natural logarithm?\nA) 2.718\nB) 3.141\nC) 1.618\nD) 2.236\nOutput only the letter.", "A"),
    ("tectonic_know_26", "Knowledge", "mcq", "Which particle has a negative charge?\nA) Proton\nB) Neutron\nC) Electron\nD) Positron\nOutput only the letter.", "C"),
    ("tectonic_know_27", "Knowledge", "mcq", "What is the Earth's approximate circumference in km?\nA) 20,000\nB) 30,000\nC) 40,000\nD) 50,000\nOutput only the letter.", "C"),
    ("tectonic_know_28", "Knowledge", "mcq", "What is the power of a 100-watt bulb operating for 10 hours in watt-hours?\nA) 100\nB) 500\nC) 1000\nD) 10000\nOutput only the letter.", "C"),
    ("tectonic_know_29", "Knowledge", "mcq", "What is the half-life of Carbon-14 in years?\nA) 2,730\nB) 5,730\nC) 11,460\nD) 22,920\nOutput only the letter.", "B"),
    ("tectonic_know_30", "Knowledge", "mcq", "How many teeth does a typical adult human have?\nA) 28\nB) 30\nC) 32\nD) 34\nOutput only the letter.", "C"),
    ("tectonic_know_31", "Knowledge", "mcq", "What is the smallest prime number?\nA) 0\nB) 1\nC) 2\nD) 3\nOutput only the letter.", "C"),
    ("tectonic_know_32", "Knowledge", "mcq", "What is the acceleration due to gravity on Earth in m/s^2?\nA) 8.9\nB) 9.8\nC) 10.8\nD) 11.2\nOutput only the letter.", "B"),
    ("tectonic_know_33", "Knowledge", "mcq", "Which scientist proposed the theory of general relativity?\nA) Newton\nB) Bohr\nC) Einstein\nD) Planck\nOutput only the letter.", "C"),
    ("tectonic_know_34", "Knowledge", "mcq", "What type of bond shares electrons between atoms?\nA) Ionic\nB) Metallic\nC) Covalent\nD) Hydrogen\nOutput only the letter.", "C"),
    ("tectonic_know_35", "Knowledge", "mcq", "What is the sum of angles in a quadrilateral?\nA) 180\nB) 270\nC) 360\nD) 540\nOutput only the letter.", "C"),
    ("tectonic_know_36", "Knowledge", "mcq", "What is the symbol for the element Potassium?\nA) Po\nB) Pt\nC) K\nD) P\nOutput only the letter.", "C"),
    ("tectonic_know_37", "Knowledge", "mcq", "What is the binary representation of decimal 7?\nA) 100\nB) 101\nC) 110\nD) 111\nOutput only the letter.", "D"),
    ("tectonic_know_38", "Knowledge", "mcq", "What is the function of red blood cells?\nA) Fight infection\nB) Carry oxygen\nC) Clot blood\nD) Produce antibodies\nOutput only the letter.", "B"),
    ("tectonic_know_39", "Knowledge", "mcq", "Which planet is known as the Red Planet?\nA) Venus\nB) Jupiter\nC) Mars\nD) Mercury\nOutput only the letter.", "C"),
    ("tectonic_know_40", "Knowledge", "mcq", "What is the formula for sulfuric acid?\nA) H2SO3\nB) H2SO4\nC) H2O\nD) H2S\nOutput only the letter.", "B"),
]
for q in know_qs:
    QUESTIONS.append({
        "task_id": q[0],
        "category": q[1],
        "type": q[2],
        "prompt": q[3],
        "answer": q[4],
    })

# ===== TOOL CALLING (40 questions) =====

tool_qs = [
    ("tectonic_tool_01", "Tool Calling", "function_call", "You are a weather assistant. Call the function `get_forecast` with arguments: city='Tokyo', days=3. Output a JSON function call.", "get_forecast"),
    ("tectonic_tool_02", "Tool Calling", "function_call", "You are a calculator. Call the function `calculate` with arguments: expression='(15+27)*4', precision=2. Output a JSON function call.", "calculate"),
    ("tectonic_tool_03", "Tool Calling", "function_call", "Call `send_email` with arguments: to='alice@example.com', subject='Meeting', body='Confirmed for tomorrow at 10am'. Output a JSON function call.", "send_email"),
    ("tectonic_tool_04", "Tool Calling", "function_call", "Call `search_database` with: query='SELECT * FROM employees WHERE salary > 50000', limit=10. Output a JSON function call.", "search_database"),
    ("tectonic_tool_05", "Tool Calling", "function_call", "Call `translate_text` with: text='Bonjour le monde', source='fr', target='en'. Output a JSON function call.", "translate_text"),
    ("tectonic_tool_06", "Tool Calling", "function_call", "Call `book_flight` with: origin='JFK', destination='LHR', date='2026-08-15', passengers=2. Output a JSON function call.", "book_flight"),
    ("tectonic_tool_07", "Tool Calling", "function_call", "Call `create_user` with: username='jdoe', role='admin', email='jdoe@example.com'. Output a JSON function call.", "create_user"),
    ("tectonic_tool_08", "Tool Calling", "function_call", "Call `analyze_sentiment` with: text='The product is absolutely amazing and works perfectly!'. Output a JSON function call.", "analyze_sentiment"),
    ("tectonic_tool_09", "Tool Calling", "function_call", "Call `upload_file` with: filename='report.pdf', destination='/documents/', overwrite=true. Output a JSON function call.", "upload_file"),
    ("tectonic_tool_10", "Tool Calling", "function_call", "Call `generate_report` with: report_type='quarterly', year=2026, quarter=2, format='pdf'. Output a JSON function call.", "generate_report"),
    ("tectonic_tool_11", "Tool Calling", "function_call", "Call `schedule_meeting` with: title='Sprint Review', attendees=['alice', 'bob', 'charlie'], duration_minutes=30. Output a JSON function call.", "schedule_meeting"),
    ("tectonic_tool_12", "Tool Calling", "function_call", "Call `convert_currency` with: amount=1000, from_currency='USD', to_currency='EUR'. Output a JSON function call.", "convert_currency"),
    ("tectonic_tool_13", "Tool Calling", "function_call", "Call `find_restaurant` with: cuisine='italian', location='Manhattan', min_rating=4.0, max_price=50. Output a JSON function call.", "find_restaurant"),
    ("tectonic_tool_14", "Tool Calling", "function_call", "Call `set_reminder` with: task='Buy groceries', datetime='2026-07-05T09:00:00', recurring=false. Output a JSON function call.", "set_reminder"),
    ("tectonic_tool_15", "Tool Calling", "function_call", "Call `train_model` with: dataset='customer_churn.csv', algorithm='random_forest', test_split=0.2, random_state=42. Output a JSON function call.", "train_model"),
    ("tectonic_tool_16", "Tool Calling", "function_call", "Call `get_stock_price` with: symbol='AAPL', interval='1d', range='1mo'. Output a JSON function call.", "get_stock_price"),
    ("tectonic_tool_17", "Tool Calling", "function_call", "Call `compile_code` with: source_code='print(\"Hello\")', language='python', optimize=true. Output a JSON function call.", "compile_code"),
    ("tectonic_tool_18", "Tool Calling", "function_call", "Call `order_pizza` with: size='large', toppings=['pepperoni', 'mushrooms', 'olives'], quantity=2. Output a JSON function call.", "order_pizza"),
    ("tectonic_tool_19", "Tool Calling", "function_call", "Call `reset_password` with: user_id=1057, email='user@example.com', method='email_link'. Output a JSON function call.", "reset_password"),
    ("tectonic_tool_20", "Tool Calling", "function_call", "Call `run_query` with: endpoint='https://api.example.com/data', params={'page': 1, 'per_page': 50}, timeout=30. Output a JSON function call.", "run_query"),
    ("tectonic_tool_21", "Tool Calling", "function_call", "Call `generate_image` with: prompt='A serene mountain landscape at sunset', style='oil_painting', resolution='1920x1080'. Output a JSON function call.", "generate_image"),
    ("tectonic_tool_22", "Tool Calling", "function_call", "Call `validate_json` with: json_string='{\"name\": \"test\"}', schema='person_schema_v2'. Output a JSON function call.", "validate_json"),
    ("tectonic_tool_23", "Tool Calling", "function_call", "Call `subscribe_newsletter` with: email='user@domain.com', topics=['tech', 'science', 'AI'], frequency='weekly'. Output a JSON function call.", "subscribe_newsletter"),
    ("tectonic_tool_24", "Tool Calling", "function_call", "Call `encode_token` with: payload={'user_id': 42, 'role': 'moderator'}, algorithm='HS256', expires_in=3600. Output a JSON function call.", "encode_token"),
    ("tectonic_tool_25", "Tool Calling", "function_call", "Call `calculate_distance` with: point_a={'lat': 40.7128, 'lon': -74.0060}, point_b={'lat': 34.0522, 'lon': -118.2437}, unit='km'. Output a JSON function call.", "calculate_distance"),
    ("tectonic_tool_26", "Tool Calling", "function_call", "Call `add_to_cart` with: product_id='PROD-7842', quantity=3, variant='blue'. Output a JSON function call.", "add_to_cart"),
    ("tectonic_tool_27", "Tool Calling", "function_call", "Call `optimize_route` with: waypoints=['NYC', 'Boston', 'Philadelphia', 'DC'], optimize_for='time'. Output a JSON function call.", "optimize_route"),
    ("tectonic_tool_28", "Tool Calling", "function_call", "Call `generate_summary` with: article_url='https://example.com/long-article', max_length=200, language='en'. Output a JSON function call.", "generate_summary"),
    ("tectonic_tool_29", "Tool Calling", "function_call", "Call `detect_objects` with: image_url='https://example.com/photo.jpg', confidence_threshold=0.75, return_labels=true. Output a JSON function call.", "detect_objects"),
    ("tectonic_tool_30", "Tool Calling", "function_call", "Call `allocate_resources` with: project='Orion', cpu_cores=8, ram_gb=32, storage_gb=500, environment='production'. Output a JSON function call.", "allocate_resources"),
    ("tectonic_tool_31", "Tool Calling", "function_call", "Call `log_event` with: level='error', message='Database connection timeout after 30s', service='api-gateway', timestamp='2026-07-04T12:00:00Z'. Output a JSON function call.", "log_event"),
    ("tectonic_tool_32", "Tool Calling", "function_call", "Call `fetch_pull_requests` with: repo='owner/repo', state='open', sort='updated', direction='desc'. Output a JSON function call.", "fetch_pull_requests"),
    ("tectonic_tool_33", "Tool Calling", "function_call", "Call `compute_statistics` with: data=[23, 45, 67, 89, 12, 34, 56, 78], metrics=['mean', 'median', 'std'], round_to=2. Output a JSON function call.", "compute_statistics"),
    ("tectonic_tool_34", "Tool Calling", "function_call", "Call `deploy_service` with: service_name='auth-service', version='2.1.0', replicas=3, strategy='rolling_update'. Output a JSON function call.", "deploy_service"),
    ("tectonic_tool_35", "Tool Calling", "function_call", "Call `analyze_logs` with: log_file='server.log', search_pattern='ERROR|CRITICAL', time_range={'start': '2026-07-01', 'end': '2026-07-03'}. Output a JSON function call.", "analyze_logs"),
    ("tectonic_tool_36", "Tool Calling", "function_call", "Call `generate_visualization` with: chart_type='bar', x_labels=['Q1','Q2','Q3','Q4'], values=[150, 230, 180, 310], title='Quarterly Revenue'. Output a JSON function call.", "generate_visualization"),
    ("tectonic_tool_37", "Tool Calling", "function_call", "Call `process_payment` with: amount=49.99, currency='USD', method='credit_card', customer_id='CUST-8912'. Output a JSON function call.", "process_payment"),
    ("tectonic_tool_38", "Tool Calling", "function_call", "Call `test_endpoint` with: url='https://api.example.com/health', method='GET', expected_status=200, timeout_ms=5000. Output a JSON function call.", "test_endpoint"),
    ("tectonic_tool_39", "Tool Calling", "function_call", "Call `schedule_backup` with: source_dir='/var/data', dest_bucket='backups-prod', cron_schedule='0 2 * * *', retention_days=30. Output a JSON function call.", "schedule_backup"),
    ("tectonic_tool_40", "Tool Calling", "function_call", "Call `recommend_similar` with: item_id='MOV-2049', category='science_fiction', limit=5, include_reasons=true. Output a JSON function call.", "recommend_similar"),
]
for q in tool_qs:
    QUESTIONS.append({
        "task_id": q[0],
        "category": q[1],
        "type": q[2],
        "prompt": q[3],
        "answer": q[4],
    })


def main():
    output_dir = os.path.join(os.path.dirname(__file__), "..", "data")
    output_path = os.path.join(output_dir, "tectonic_full.json")
    os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(QUESTIONS, f, indent=2)
    print(f"Generated {len(QUESTIONS)} questions -> {output_path}")

    # Count categories
    from collections import Counter
    cats = Counter(q["category"] for q in QUESTIONS)
    for cat, cnt in sorted(cats.items()):
        print(f"  {cat}: {cnt}")


if __name__ == "__main__":
    main()
